# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false


[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](black)'

[nodejs]
symbol = 'ğŸ´ '


